import os
import json
import requests
from dotenv import load_dotenv

# Load environment variables
load_dotenv()
VAPI_API_KEY = os.getenv("VAPI_API_KEY")

def deploy_to_vapi(config_path, mock_mode=False):
    """Deploys the agent config to Vapi.ai."""
    print("Deploying to Vapi...")
    
    if mock_mode:
        print("Mock Mode: Skipping Vapi Deployment.")
        return "mock-assistant-id"

    if not VAPI_API_KEY:
        print("Error: VAPI_API_KEY is missing. Cannot deploy.")
        return None

    # Load the config generated by the Architect
    with open(config_path, "r") as f:
        agent_config = json.load(f)

    # Construct Vapi Payload
    # Note: This is a simplified payload. Vapi has many options.
    payload = {
        "name": agent_config.get("agent_name", "My AI Agent"),
        "voice": {
            "voiceId": agent_config.get("voice_id", "jennifer-playht"),
            "provider": "playht"
        },
        "model": {
            "model": "gpt-4o",
            "messages": [
                {
                    "role": "system",
                    "content": agent_config.get("system_prompt", "You are a helpful assistant.")
                }
            ]
        },
        "firstMessage": agent_config.get("first_message", "Hello!"),
        "transcriber": {
            "provider": "deepgram",
            "model": "nova-2",
            "language": "en"
        }
    }

    headers = {
        "Authorization": f"Bearer {VAPI_API_KEY}",
        "Content-Type": "application/json"
    }

    try:
        response = requests.post("https://api.vapi.ai/assistant", json=payload, headers=headers)
        
        if response.status_code == 201:
            data = response.json()
            assistant_id = data.get("id")
            print(f"Success! Assistant ID: {assistant_id}")
            
            # Vapi doesn't give a direct 'demo link' in the API response usually, 
            # but we can construct one if we have a frontend, or use their dashboard link.
            # For now, we'll return the ID.
            return assistant_id
        else:
            print(f"Vapi Error: {response.text}")
            return None
            
    except Exception as e:
        print(f"Deployment failed: {e}")
        return None

if __name__ == "__main__":
    import argparse
    parser = argparse.ArgumentParser(description="Deploy Voice Agent to Vapi")
    parser.add_argument("--config", default="agent_config.json", help="Path to agent config JSON")
    parser.add_argument("--mock", action="store_true", help="Run in mock mode")
    args = parser.parse_args()
    
    deploy_to_vapi(args.config, args.mock)
